{% set version = "0.1.dev0" %}

package:
  name: sound_field_analysis
  version: {{ version }}

source:
  path: sound_field_analysis
  #git_url: https://github.com/QULab/sofia-py.git

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - scipy
    - plotly

test:
  imports:
    - sound_field_analysis

about:
  home: https://github.com/QULab/sound_field_analysis-py
  license: GPLv3
  license_file: LICENSE
  summary: Analyze, visualize and process sound field data recorded by spherical microphone arrays

